import '../styles/globals.css'
import styles from '../styles/Home.module.css'
import { Roboto } from '@next/font/google'
import { BsHouseFill } from "react-icons/bs"
import Link from 'next/link'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Script from 'next/script'

const roboto = Roboto({ weight: '400' })

export default function App({ Component, pageProps }) {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>cabChat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/cabbage.png" />
        <link rel="manifest" href="/manifest.json" />
        <Script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8470071689417907"
          crossorigin="anonymous"></Script>
      </Head>
      {
        router.pathname !== '/' ?
          <Link href={'/'}>
            <section className={styles.header}>
              <BsHouseFill size={20} />
              <span style={roboto.style}>Home</span>
            </section>
          </Link>
          :
          null
      }

      <Component {...pageProps} />
    </>
  )
}
